### ISSUE TITLE
Téléchargement de PyCharm

### ISSUE THREAD

**Issue by Orulirn** [Lycee-Experimental/django-lxp#4]
sudo wget -c https://download-cdn.jetbrains.com/python/pycharm-professional-2021.3.tar.gz -O - | sudo tar -xz -C ~/opt/
--2022-01-11 17:42:24--  https://download-cdn.jetbrains.com/python/pycharm-professional-2021.3.tar.gz
Résolution de download-cdn.jetbrains.com (download-cdn.jetbrains.com)... 13.225.39.26, 13.225.39.58, 13.225.39.50, ...
Connexion vers download-cdn.jetbrains.com (download-cdn.jetbrains.com)|13.225.39.26|:443... connecté.
requête HTTP transmise, en attente de la réponse... 200 OK
Taille : 640428858 (611M) [binary/octet-stream]
Enregistre : «STDOUT»

-                                            0%[                                                                                      ]       0  --.-KB/s               tar: /home/ewen/opt : open impossible: Aucun fichier ou dossier de ce type
tar: Error is not recoverable: exiting now
-                                            0%[                                                                                      ] 284,67K  --.-KB/s    ds 0,1s    

Impossible d'écrire dans «-» (Succès).

je comprends pas trop l'erreure... tout ça pour dire que j'arrive pas a installer PyCharme ce qui est dommage.

**Comment by davy39** [comment]
C'est étrange, il cherche à le télécharger dans le dossier **~**/opt (cad /home/ewen/opt) et non à la racine /opt.
Il me semble que je m'étais planté dans une version précédente du wiki, mais l'erreur me semble pourtant corrigée dans la [version actuelle](https://github.com/Lycee-Experimental/django-lxp/wiki/2.-Configuration-de-l'IDE-PyCharm).

Peux-tu réessayer la manip ?
